### ISSUE TITLE
DockBlock Indentation

### ISSUE THREAD

**Issue by akalongman** [phpfmt/fmt#124] opened 2016-03-21 10:53 UTC
Description:
Is this possible to indent DockBlock correctly?

Failing code:
```php
<?php

namespace App\Domain\Services\PaymentSchedule;

class RegisterRoleService
{
/**
* @param  $id
* @param  $name
* @return $degree
*/
public function run($id, $name, $degree)
{
$this->save($role);
$role = $this->find($role->id());
return $role;
}
}
```

Expected result:
```php
<?php

namespace App\Domain\Services\PaymentSchedule;

class RegisterRoleService
{
    /**
     * @param  $id
     * @param  $name
     * @return $degree
     */
    public function run($id, $name, $degree)
    {
        $this->save($role);
        $role = $this->find($role->id());
        return $role;
    }
}
```

Actual result:
```php
<?php

namespace App\Domain\Services\PaymentSchedule;

class RegisterRoleService
{
/**
 * @param  $id
 * @param  $name
 * @return $degree
 */
    public function run($id, $name, $degree)
    {
        $this->save($role);
        $role = $this->find($role->id());
        return $role;
    }
}

```

Passes in configuration:
```
"ReindentSwitchBlocks",
"OrderAndRemoveUseClauses",
"PSR2EmptyFunction",
"StripSpaceWithinControlStructures",
"ShortArray",
"SpaceBetweenMethods",
"AutoSemicolon",
"MergeElseIf",
"PrettyPrintDocBlocks",
"RemoveSemicolonAfterCurly"
```

**Comment by ccirello** [comment] 2016-03-21 11:01
By design, phpfmt will not touch comments and doc blocks in the first column. It can be easily addressed by adding a space before the doc block - it will indent after that.

**Closed by ccirello** 2016-03-21 11:01 UTC
