### ISSUE TITLE
Fatal error from failed typecheck at fmt.stub.php:6054

### ISSUE THREAD

**Issue by nickion** [phpfmt/fmt#153] opened 2016-05-30 14:46 UTC
Description:
```
Formatting a file throws an uncaught typecheck exception. 
This seems to be a regression in AllmanStyleBraces. 
```

Failing code:
```
<?php

$di->set('x', function () {
});

Testing outside of sublime with:
c:/php-7.0.5/php.exe 'C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar' '--config=C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/php.tools.ini' '--psr2' '--smart_linebreak_after_curly' '--passes=AlignDoubleArrow,AlignDoubleSlashComments,DoubleToSingleQuote,SpaceBetweenMethods,StripNewlineAfterCurlyOpen,AddMissingParentheses,AllmanStyleBraces,StripExtraCommaInArray,ShortArray,ReindentSwitchBlocks' '-v' '-o=-' '-' < /cygdrive/r/web/app/config/webservices.php
Used passes: EliminateDuplicatedEmptyLines, RTrim, StripExtraCommaInArray, ShortArray, StripNewlineAfterCurlyOpen, PSR2IndentWithSpace, AllmanStyleBraces, LeftAlignComment, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2LnAfterNamespace, PSR2KeywordsLowerCase, PSR2IndentImplements, ReindentEqual, Reindent, ReindentObjOps, AlignDoubleSlashComments, AlignDoubleArrow, ReindentSwitchBlocks, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderAndRemoveUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine, SpaceBetweenMethods, AddMissingParentheses, DoubleToSingleQuote
```

Expected result:
```
Code should be formatted.
```

Actual result:
```
Fatal error: Uncaught TypeError: substr_count() expects parameter 3 to be integer, boolean given in phar://C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php:6054
Stack trace:
#0 phar://C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php(6054): substr_count(' ', '\t', false)
#1 phar://C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php(1652): AllmanStyleBraces->format('<?php\n\n//use Ph...')
#2 phar://C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php(12413): BaseCodeFormatter->formatCode('<?php\n\n//use Ph...')
#3 C:\Users\Foo\AppData\Roaming\Sublime Text 3\Packages\phpfmt\fmt.phar(10): include('phar://C:/Users...')
#4 {main}
  thrown in phar://C:/Users/Foo/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php on line 6054
```

Your configuration:
```
PHP 7.0.5
```

phpfmt engine channel and branch:
```
lts/803.4
```

**Comment by ccirello** [comment] 2016-05-30 14:48
please follow the issue template.

**Comment by ccirello** [comment] 2016-05-30 15:00
Provide a code example that demonstrate this failure.

**Comment by ccirello** [comment] 2016-05-30 15:00
> No test case available at this time. Will update if a smaller example gives the same failure.

I am closing this issue until you are able to provide a reproducible test with code.

**Comment by nickion** [comment] 2016-05-30 15:13
Updated with trivial code in a moment. You marked it as question rather than the bug that it is, so I'll take the chance to ask one if that's ok, and it's this. Given that the example is simple, why has this bug crept in and not been caught in regression testing?

**Comment by ccirello** [comment] 2016-05-30 15:18
> why has this bug crept in and not been caught in regression testing?

Because the coverage for AllmanStyleBraces is very low. It is removed in alpha branch and once this LTS is EOL'd it will be removed.

**Comment by nickion** [comment] 2016-05-30 15:22
Thanks for the quick updates Carlos. So Allman support is effectively deprecated now and due to be removed?

**Comment by ccirello** [comment] 2016-05-30 15:23
> So Allman support is effectively deprecated now and due to be removed?

Yes.

Update to LTS 803.5

**Closed by ccirello** 2016-05-30 15:23 UTC
Labels: bug
