### ISSUE TITLE
Undefined variable: touchedFunction on RemoveSemicolonAfterCurly

### ISSUE THREAD

**Issue by akalongman** [phpfmt/fmt#121] opened 2016-03-21 08:26 UTC
Command
```
fmt.phar --psr2 --indent_with_space=4 --enable_auto_align --visibility_order --smart_linebreak_after_curly --passes=ReindentSwitchBlocks,OnlyOrderUseClauses,PSR2EmptyFunction,StripSpaceWithinControlStructures,ShortArray,SpaceBetweenMethods,AutoSemicolon,MergeElseIf,PrettyPrintDocBlocks,RemoveSemicolonAfterCurly ./AnyFile.php
```

Output:
```
PHP Notice:  Undefined variable: touchedFunction in phar:///home/longman/.composer/vendor/phpfmt/fmt/fmt.phar/fmt.stub.php on line 11292
PHP Stack trace:
PHP   1. {main}() /home/longman/.composer/vendor/phpfmt/fmt/fmt.phar:0
PHP   2. include() /home/longman/.composer/vendor/phpfmt/fmt/fmt.phar:10
PHP   3. BaseCodeFormatter->formatCode() phar:///home/longman/.composer/vendor/phpfmt/fmt/fmt.phar/fmt.stub.php:13782
PHP   4. RemoveSemicolonAfterCurly->format() phar:///home/longman/.composer/vendor/phpfmt/fmt/fmt.phar/fmt.stub.php:3024
```

phpfmt version 19.6.3

**Comment by ccirello** [comment] 2016-03-21 09:26
Please, follow the issue template always. The part of the broken code is missing.

**Comment by akalongman** [comment] 2016-03-21 09:27
Code not broken. Only notice appears

**Comment by ccirello** [comment] 2016-03-21 09:28
But without the failing code I cannot reproduce the notice message.

**Comment by akalongman** [comment] 2016-03-21 09:31
Try enable transformations:

```
ReindentSwitchBlocks,
OrderAndRemoveUseClauses,
PSR2EmptyFunction,
StripSpaceWithinControlStructures,
ShortArray,
SpaceBetweenMethods,
AutoSemicolon,
MergeElseIf,
PrettyPrintDocBlocks,
RemoveSemicolonAfterCurly
```

**Comment by ccirello** [comment] 2016-03-21 09:32
Ok. I am going to try to approach this in a different way. Don't you have a piece of code that triggers this notice somehow? We both know it affects only one pass. But it is important to be able to reproduce an error and not just provide a fix that doesn't extrapolate into more causes.

**Comment by akalongman** [comment] 2016-03-21 09:34
Ok. File content:

```php
<?php

namespace Tests\Acceptance\Api;

use App\Domain\Models\Identity\Values\RoleId;
use TestCase;

/**
 * @group api
 */
class RoleTest extends TestCase
{

    public function setUp()
    {
        parent::setUp();

        $this->initTestUser();
    }

    /**
     * @test
     */
    public function get_role_list_should_be_authorized()
    {
        $this->json('GET', $this->apiUri('role'))
            ->seeStatusCode(401);
    }

    /**
     * @test
     */
    public function get_role_list()
    {
        $this->be($this->user);

        $this->json('GET', $this->apiUri('role'))
            ->seeJson(['name' => config('testing.role.name')]);
    }

    /**
     * @test
     */
    public function get_role_by_id_should_be_authorized()
    {
        $this->json('GET', $this->apiUri('role/' . config('testing.role.id')))
            ->seeStatusCode(401);
    }

    /**
     * @test
     */
    public function get_role_by_id()
    {
        $this->be($this->user);

        $this->json('GET', $this->apiUri('role/' . config('testing.role.id')))
            ->seeJson(['name' => config('testing.role.name')]);
    }

    /**
     * @test
     */
    public function store_role_should_be_authorized()
    {
        $id   = RoleId::generate()->toString();
        $post = [
            'id'   => $id,
            'name' => 'სატესტო როლი 3',
        ];

        $this->json('POST', $this->apiUri('role'), $post)
            ->seeStatusCode(401);
    }

    /**
     * @test
     */
    public function store_role()
    {
        $this->be($this->user);
        $id   = RoleId::generate()->toString();
        $post = [
            'id'   => $id,
            'name' => 'სატესტო როლი 3',
        ];

        $this->json('POST', $this->apiUri('role'), $post);
            //->seeJson($post);
$this->dump();

    }

    /**
     * @test
     */
    public function update_role_should_be_authorized()
    {
        $id = RoleId::generate()->toString();

        $put = [
            'name' => 'სატესტო როლი 100',
        ];
        $this->json('PUT', $this->apiUri('role/' . $id), $put)
            ->seeStatusCode(401);
    }

    /**
     * @test
     */
    public function update_role()
    {
        $this->be($this->user);

        $id   = RoleId::generate()->toString();
        $post = [
            'id'   => $id,
            'name' => 'სატესტო როლი 3',
        ];

        $this->json('POST', $this->apiUri('role'), $post)
            ->seeJson($post);

        $put = [
            'name'     => 'სატესტო როლი 100',
            'position' => 10,
        ];
        $this->json('PUT', $this->apiUri('role/' . $id), $put)
            ->seeJson([
                'id'   => $id,
                'name' => 'სატესტო როლი 100',
            ]);

        //->seeInDatabase('banks', ['name' => 'სატესტო ბანკი 111113']);
    }
}

```

**Comment by ccirello** [comment] 2016-03-21 09:35
Thanks.

**Comment by ccirello** [comment] 2016-03-21 09:58
Fixed by https://github.com/phpfmt/fmt/commit/36d7682492f58c8ebac212c491de4a94ca1aacd5

**Closed by ccirello** 2016-03-21 09:58 UTC
Labels: bug
